openapi: 3.0.0
info:
  title: My API
  description: My API description
  version: 1.0.0
servers:
  - url: https://guarded-depths-92423.herokuapp.com/api
paths:
  /company: 
    get:
      summary: Get a list of companies
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        type:
                          type: string
                          enum:
                            - company
                        attributes:
                          type: object
                          properties:
                            name:
                              type: string
    post:
      summary: Create a new company
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Created
  /company/{companyId}:
    get:
      summary: Get a company by ID
      parameters:
        - name: companyId
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      type:
                        type: string
                        enum:
                          - company
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
        "404":
          description: Not Found
  /card/{cardID}:
    get:
      summary: Get a card by ID
      parameters:
        - name: cardID
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      id:
                        type: integer
                      attributes:
                        type: object
                        properties:
                          name:
                            type: string
        "404":
          description: Not Found
  /transactions/{cardID}:
    get:
      summary: Get transactions for a card by ID
      parameters:
        - name: cardID
          in: path
          required: true
          schema:
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      type: object
                      properties:
                        id:
                          type: integer
                        attributes:
                          type: object
                          properties:
                            description:
                              type: string
                            amount:
                              type: number
                            date:
                              type: string
        "404":
          description: Not Found